apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: moloch
  labels:
    component: moloch
spec:
  serviceName: moloch
  replicas: {{ groups['sensors'] | length }} #{{ groups['moloch'] | length }}
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      component: moloch
  template:
    metadata:
      labels:
        component: moloch
    spec:
      hostNetwork: true
      containers:
      - name: "moloch"
        image: "{{ moloch_image}}:{{ moloch_tag }}"
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
              - SYS_NICE
        ports:
          - containerPort: {{ moloch_port }}
            name: webgui
        resources:
          limits:
            cpu: {{ moloch_cpu_limit }}
          requests:
            cpu: {{ moloch_cpu_request }}
        volumeMounts:
        - name: vars
          mountPath: /etc/icdm/
        - name: templates
          mountPath: /etc/icdm/templates/
        - name: configs
          mountPath: /etc/icdm/conf/
        - name: data
          mountPath: "{{ moloch_pcap_path }}"
      restartPolicy: Always
      volumes:
{% if not use_ceph_for_pcap %}
      - name: data
        hostPath:
          path: {{ moloch_pcap_folder }}
{% endif %}
      - name: vars
        configMap:
          name: vars
      - name: configs
        configMap:
          name: moloch
          items:
          - key: config.ini.conf
            path: config.ini.conf
      - name: templates
        configMap:
          name: moloch
          items:
          - key: config.ini.tmpl
            path: config.ini.tmpl
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions: 
              - key: component
                operator: In
                values:
                - moloch
            topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: moloch
                operator: In
                values:
                - "true"
              - key: role
                operator: In
                values:
                - "sensor"
{% if use_ceph_for_pcap %}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: rbd
      resources:
        requests:
          storage: {{ moloch_pcap_pv_size }}Gi
{% endif %}
